Updated distributed network manual
panda3d/panda3d-docs pull request #70
Opened 2020-06-15 11:58 UTC by fireclawthefox

Added information regarding base and simbase repositories
Added further information for how to use distributed smooth nodes

2020-06-15 13:45 UTC, rdb requested changes
Thanks for your work on this!

Ignore the linkcheck failure, it seems to be unrelated to your changes.

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/distributed-smooth-node.rst
> +The make use of the smoothing functionality and automatically broadcasting of
"*To* make use of", I assume this should be.

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/client-repositories.rst
> +instance in a variable called cr. Just like in the following.
This is not a complete sentence.  You can tack it on the end of the previous one.  I would suggest:
```rest
instance in a variable called ``cr``, as in the following example:
```

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/distributed-smooth-node.rst
> +few frames dependent on how fast the network connection is. Though, even if they
Missing comma between "frames" and "dependent"

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/distributed-smooth-node.rst
> +move smooth, they may lag behind by some amount. Therefor, the prediction flag
adverb of smooth is "smoothly"

"therefore" needs a final e

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/distributed-smooth-node.rst
> +would be overwritten by the update task.
"As it…" is not a complete sentence, but you can tack it onto the previous one with a comma.

2020-06-15 13:45 UTC, rdb commented on programming/networking/distributed/distributed-smooth-node.rst
> +The make use of the smoothing functionality and automatically broadcasting of
Also, "automatic broadcasting", I think, since "automatic" is an adjective to the noun "broadcasting" here.

2020-06-16 05:36 UTC, fireclawthefox commented
@rdb thanks, everything should be fixed now.

2020-06-16 20:16 UTC, rdb approved these changes
Thanks!

2020-06-16 20:17 UTC, merged